### ISSUE TITLE
Adding header on soap request

### ISSUE THREAD

**Issue by ghost** [WsdlToPhp/PackageGenerator#195]
SO this my code : 

```

<?php

require_once __DIR__ . '/vendor/autoload.php';

$url = 'https://api-demo?wsdl';
$key = 'X-Key';
$code = 'sdf1sdfsdf4sd56f4ds3f1sd3f31sdNL';

use WsdlToPhp\PackageGenerator\ConfigurationReader\GeneratorOptions;
use WsdlToPhp\PackageGenerator\Generator\Generator;

$options = array(
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_URL => $url,
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_CLASSMAP => ClassMap::get(),
);
/**
 * Samples for Refund ServiceType
 */
$refund = new \ServiceType\Refund($options);
$requesterCredentials = new \StructType\CustomSecurityHeaderType(/*[...])*/);
$refund->setSoapHeaderRequesterCredentials($requesterCredentials);
$refund->setHttpHeader($key, $code);

/**
 * Sample call for RefundTransaction operation/method
 */
if ($refund->RefundTransaction(new \StructType\RefundTransactionReq()) !== false) {
    print_r($refund->getResult());
} else {
    print_r($refund->getLastError());
}
```

so when i lunch this i have : 

```
PHP Fatal error:  Uncaught Error: Class 'ClassMap' not found ingenerateWSDSL2.php:19
Stack trace:
#0 {main}
  thrown ingenerateWSDSL2.php on line 19
```

why ?
what ç forget please ?

and my purpose is create requet with api key header how do that please ?

thanks

**Comment by mikaelcom** [comment]
Please read carefully the section [Usage](https://github.com/WsdlToPhp/PackageGenerator#usage) and the corresponding links. Let me now then.

**Comment by Spartacus2018** [comment]
sorry, 
i mnot understand, i can get my packtage with not header wsdl, but when i need to put header information, no way to get my generate code ??

**Comment by Spartacus2018** [comment]
Ok so i think i start to understand

first of all, i have to get my wsdl in file and generate a project wsdl with command line.

when i get my project i go to the tutorial.php and i try to use the header soap effect.


but for now it's a little difficult to understand how to add the header.

**Comment by Spartacus2018** [comment]
still not working, i can't pass the header on my request

**Comment by mikaelcom** [comment]
Yes you can! Any header can be set, you have to take your time to fully understand how it can be done knowing it can be done eventually.
What are the headers you have to pass ?

**Comment by Spartacus2018** [comment]
Hello,
 i get an webservice WSDL accesing by the url : 

```
$url = "https://appi.gouv.com/Gdream_process?wsdl" //
to acess to this wsdl i need to add some header parametre : 
$header = "X-Api-Key:LOKHFiifjhfhjOIHJFKOLQHDSM2545L";
```

So i start using u looking good project : 


```
$ mkdir Project01
$ composer require wsdltophp/packagegenerator
$ wget https://phar.wsdltophp.com/wsdltophp-php7.phar
$ chmod +x wsdltophp-php7.phar
```

so i get this error for my first try : 

```
$ ./wsdltophp-php7.phar generate:package --urlorpath="https://api-pp-test.sa-cim.fr/GED/wsImportDocGED.asmx?WSDL" --destination="./MySdk" --composer-name="myproject/mysdk"  --force
 Start at 2019-06-07 19:12:27
PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://appi.gouv.com/Gdream_process?wsdl"' : failed to load external entity "https://appi.gouv.com/Gdream_process?wsdl""
 in phar:///wsdltophp-php7.phar/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php on line 82
PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://appi.gouv.com/Gdream_process?wsdl"' : failed to load external entity "https://appi.gouv.com/Gdream_process?wsdl""
 in phar:///wsdltophp-php7.phar/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php on line 82

In GeneratorSoapClient.php line 33:

  Unable to load WSDL at "https://appi.gouv.com/Gdream_process?wsdl""!


In AbstractSoapClientBase.php line 82:

  SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://appi.gouv.com/Gdream_process?wsdl"' : fail
  ed to load external entity "https://appi.gouv.com/Gdream_process?wsdl""


generate:package [--force] [--urlorpath URLORPATH] [--destination DESTINATION] [--login [LOGIN]] [--password [PASSWORD]] [--proxy-host [PROXY-HOST]] [--proxy-port [PROXY-PORT]] [--proxy-login [PROXY-LOGIN]] [--proxy-password [PROXY-PASSWORD]] [--prefix PREFIX] [--suffix SUFFIX] [--namespace [NAMESPACE]] [--category [CATEGORY]] [--gathermethods [GATHERMETHODS]] [--gentutorial [GENTUTORIAL]] [--genericconstants [GENERICCONSTANTS]] [--addcomments [ADDCOMMENTS]] [--standalone [STANDALONE]] [--validation [VALIDATION]] [--struct [STRUCT]] [--structarray [STRUCTARRAY]] [--soapclient [SOAPCLIENT]] [--composer-name COMPOSER-NAME] [--composer-settings [COMPOSER-SETTINGS]] [--structs-folder [STRUCTS-FOLDER]] [--arrays-folder [ARRAYS-FOLDER]] [--enums-folder [ENUMS-FOLDER]] [--services-folder [SERVICES-FOLDER]] [--src-dirname [SRC-DIRNAME]] [--xsd-types-path [XSD-TYPES-PATH]] [--config [CONFIG]]
```


So i supose it's the missing header so i can't get my generation with the program wsdltophp-php7.phar

so i used Postman to download the WSDL files and i put it my project directory : 

and i lunch again the script : 

`$ user [/] > nano fluxWSDL.WSDL`
	Adding some wsdl stuff found on postman working request

Lunch the program generation with a files wsdl : 
	
```
$ user [/] > ./wsdltophp-php7.phar generate:package --urlorpath="fluxWSDL.WSDL" --destination="./MySdk" --composer-name="myproject/mysdk"  --force
 Start at 2019-06-07 19:16:38
Cannot create cache directory /home/user/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/user/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies
Dependency resolution completed in 0.000 seconds
Analyzed 84 packages to resolve dependencies
Analyzed 73 rules to resolve dependencies
Package operations: 1 install, 0 updates, 0 removals
Installs: wsdltophp/packagebase:2.0.3
  - Installing wsdltophp/packagebase (2.0.3): Downloading (100%)
 Extracting archiveWriting lock file
Generating optimized autoload files
 End at 2019-06-07 19:16:46, duration: 00:00:08
```

 so evrything looks good :) 

 and now i get my file project and my tutorial.php :)
 
 
 in the tutorial.php i change this line with the good URL :
 
 ```

 $options = array(
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_URL => 'fluxWSDL.WSDL',
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_CLASSMAP => ClassMap::get(),
);
```


by 

```
$options = array(
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_URL => 'https://appi.gouv.com/Gdream_process?wsdl',
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_CLASSMAP => ClassMap::get(),
);
```


and i lunch the tutorial.php : 


```
user [/MySdk] > php tutorial.php
PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://appi.gouv.com/Gdream_process?wsdl"' : failed to load external entity "https://appi.gouv.com/Gdream_process?wsdl""
 in /MySdk/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php on line 82
PHP Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://appi.gouv.com/Gdream_process?wsdl' : failed to load external entity "https://appi.gouv.com/Gdream_process?wsdl"
 in /MySdk/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php:82
Stack trace:
#0 /MySdk/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php(82): SoapClient->SoapClient('https://appi.go...', Array)
#1 /MySdk/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php(35): WsdlToPhp\PackageBase\AbstractSoapClientBase->initSoapClient(Array)
#2 /MySdk/tutorial.php(27): WsdlToPhp\PackageBase\AbstractSoapClientBase->__construct(Array)
#3 {main}
  thrown in /MySdk/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php on line 82
```
 
So again i think the header key is missing so i have to add it to make the request works.

now i m here.
thanks

**Comment by Spartacus2018** [comment]
ANd i try to add header stuff like u says in FAQ soap header here --



```
$options = array(
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_URL => 'https://appi.gouv.com/Gdream_process?wsdl',
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_CLASSMAP => ClassMap::get(),
);
/**
 * Samples for Ws ServiceType
 */
$ws = new \ServiceType\Ws($options);
$requesterCredentials = new \StructType\CustomSecurityHeaderType(/*[...])*/);
$ws->setSoapHeaderRequesterCredentials($requesterCredentials);
$ws->setHttpHeader('X-Api-Key', 'LOKHFiifjhfhjOIHJFKOLQHDSM2545L
```

and with this i got the same error : 


```
¨PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://appi.gouv.com/Gdream_process?wsd' : failed to load external entity "https://appi.gouv.com/Gdream_process?wsd"
 in /MySdk/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php on line 82
PHP Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://appi.gouv.com/Gdream_process?wsd' : failed to load external entity "https://appi.gouv.com/Gdream_process?wsd"
 inMySdk/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php:82
Stack trace:
#0MySdk/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php(82): SoapClient->SoapClient('https://api-pp-...', Array)
#1 MySdk/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php(35): WsdlToPhp\PackageBase\AbstractSoapClientBase->initSoapClient(Array)
#2 /MySdk/tutorial.php(27): WsdlToPhp\PackageBase\AbstractSoapClientBase->__construct(Array)
#3 {main}
 /MySdk/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php on line 82

```

**Comment by mikaelcom** [comment]
You have to create a context resource for http with the headers that you then pass in the $options array. I’m not able to put some code now, later possibly, I let you try in the meantime ;)

**Comment by Spartacus2018** [comment]
Hello there, so i try this 

first still on my tutorial.php files : 


```
$opts = array(
    'http'=>array(
      'method'=>"GET",
      'header'=>"X-Api-Key:LOKHFiifjhfhjOIHJFKOLQHDSM2545L\r\n" 
    )
  );
  
  $context = stream_context_create($opts);


/**
 * Minimal options
 */
$options = array(
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_URL => 'https://appi.gouv.com/Gdream_process?wsdl',
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_CLASSMAP => ClassMap::get(),
    $context,
  
);
```

Not working

second try : 

```
$ws = new \ServiceType\Ws($options);
$requesterCredentials = new \StructType\CustomSecurityHeaderType(/*[...])*/);
$ws->setSoapHeaderRequesterCredentials($requesterCredentials);
$ws->setHttpHeader('X-Api-Key', 'LOKHFiifjhfhjOIHJFKOLQHDSM2545L');
$ws->setSoapOptions([
    AbstractSoapClientBase::WSDL_STREAM_CONTEXT => stream_context_create([
        'https' => [
            'X-Api-Key' => 'LOKHFiifjhfhjOIHJFKOLQHDSM2545L',
        ],
    ]),
]);


```

third try  : 

```
/**
 * Minimal options
 */
$options = array(
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_URL => 'https://appi.gouv.com/Gdream_process?wsd',
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_CLASSMAP => ClassMap::get(),
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_STREAM_CONTEXT => stream_context_create([
        'https' => [
            'X-Api-Key' => 'LOKHFiifjhfhjOIHJFKOLQHDSM2545L',
        ],
    ]),
```
  

ans still on error message


`PHP Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL:                                      Couldn't load from`

**Comment by mikaelcom** [comment]
In order to see the sent request and headers in addition to the received request and headers, you can call these methods :
- $ws->getLastRequest()
- $ws->getLastRequestheaders()
- $ws->getLastResponse()
- $ws->getLastResponseheaders()

Regarding the request, I think you're near to the truth and it should be:
```php
$opts = [
    'http' => [
        'method' => "GET",
        'header' => "X-Api-Key:LOKHFiifjhfhjOIHJFKOLQHDSM2545L\r\n" 
    ]
];
$context = stream_context_create($opts);

$options = [
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_URL => 'https://appi.gouv.com/Gdream_process?wsdl',
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_CLASSMAP => ClassMap::get(),
    \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_STREAM_CONTEXT => $context,
];

$ws = new \ServiceType\Ws($options);
$requesterCredentials = new \StructType\CustomSecurityHeaderType(/*[...])*/);
$ws->setSoapHeaderRequesterCredentials($requesterCredentials);

// call the operation method
$result = $ws->callOperationMerhod();

// debug
$xmlRequest = $ws->getLastRequest();
$requestHeaders = $ws->getLastRequestheaders();

// handle the result
if (false !== $result) {
} else {
}
```

**Comment by mikaelcom** [comment]
no news, good news?
